name: notes_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  flutter_timezone: ^1.0.8
  intl: ^0.17.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
